### ISSUE TITLE
Occamy.c ?

### ISSUE THREAD

**Issue by Mounirou2003** [angeluriot/Disease_propagation#12]
![occamy](https://user-images.githubusercontent.com/50673119/76680678-d34ccd80-65ea-11ea-8130-9e33c83f8b08.png)
nieh ?

**Comment by icecodder** [comment]
@Mounirou2003 Lorsque que tu lances l'exécutable Windows peut le détecter comme un virus CE QUI N'EST PAS LE CAS ! Il suffit d'autoriser le fichier via Windows Defender ou de désactiver temporairement Windows Defender.

**Comment by Mounirou2003** [comment]
d'accord , merci
