### ISSUE TITLE
Ne peut pas être lancé sur Mac

### ISSUE THREAD

**Issue by MelvynX** [angeluriot/Disease_propagation#7]
Je ne peux pas ouvrir le fichier .exe qui donne l’application.

Je ne sais pas si le langage utiliser pour celle-ci est compatible avec MacOS, mais si c'est le cas c'est dommage que le fichier .exe ne le soit pas. 

ça m'aurait intéressé de tester ahah 😉

**Comment by TheWavesBugs** [comment]
Les fichiers .exe ne fonctionne pas sur MacOS car il sont faits pour Windows, il est donc normal que tu ne puisse l'ouvrir sur ton Mac.

**Comment by MelvynX** [comment]
Je sais ahah !

Je propose justement d'y remédier si il souhaite que se soit utiliser par plus de monde 💃

**Comment by MelvynX** [comment]
C'est bon un génie à bien taffer :
https://github.com/angeluriot/Disease_propagation/pull/8
